# Your Wi-Fi SSID and password
wifi_ssid: "WIFI"
wifi_password: "YourWifiPassword01"

marstek_m1_api_encryption_key: "1234omzUmVcVvuKfJaWBNIfuj/G3G3KvFGgQbkS5xXk="
marstek_m1_ota_password: "1234cea993cfbca3d9d808f9349cbbb0"